Fix connStr
https://gitlab.com/postgres-ai/joe/commit/26d51c369812cb75b2c4117aeae34bc896e541e7 introduced a bug leading to errors like:
```
ERROR: missing "=" after "localhost" in connection info string"
```

This is a fix for it.